name = "SwapStreams"
uuid = "0b152c4a-7e29-418b-9258-223db38db9d9"
authors = ["Zachary P. Christensen <zchristensen7@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"

[compat]
MappedArrays = "0.2"
julia = "1.4", "1.5"
